/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as DashboardRouteImport } from "./routes/_dashboard";
import { Route as ShopRouteImport } from "./routes/shop";
import { Route as SigninRouteImport } from "./routes/signin";
import { Route as DashboardIndexRouteImport } from "./routes/_dashboard/index";
import { Route as DashboardOperationsRouteImport } from "./routes/_dashboard/operations";
import { Route as DashboardReact19RouteImport } from "./routes/_dashboard/react-19";
import { Route as DashboardReportsRouteImport } from "./routes/_dashboard/reports";
import { Route as DashboardSettingsRouteImport } from "./routes/_dashboard/settings";
import { Route as DocsIndexRouteImport } from "./routes/docs.index";
import { Route as DocsSlugRouteImport } from "./routes/docs.$slug";
import { Route as LandingIndexRouteImport } from "./routes/landing.index";
import { Route as LandingAgencyRouteImport } from "./routes/landing.agency";
import { Route as LandingCourseRouteImport } from "./routes/landing.course";
import { Route as LandingEventRouteImport } from "./routes/landing.event";
import { Route as LandingProductRouteImport } from "./routes/landing.product";
import { Route as LandingSaasRouteImport } from "./routes/landing.saas";
import { Route as LandingStayRouteImport } from "./routes/landing.stay";
import { Route as ShopIndexRouteImport } from "./routes/shop.index";
import { Route as ShopProductIdRouteImport } from "./routes/shop.$productId";
import { Route as ShopCartRouteImport } from "./routes/shop.cart";
import { Route as ShopCheckoutRouteImport } from "./routes/shop.checkout";
import { Route as DashboardOrdersIndexRouteImport } from "./routes/_dashboard/orders.index";
import { Route as DashboardOrdersOrderIdRouteImport } from "./routes/_dashboard/orders.$orderId";
import { Route as DashboardProductsIndexRouteImport } from "./routes/_dashboard/products.index";
import { Route as DashboardProductsNewRouteImport } from "./routes/_dashboard/products.new";
import { Route as DashboardProjectsIndexRouteImport } from "./routes/_dashboard/projects.index";
import { Route as DashboardProjectsProjectIdRouteImport } from "./routes/_dashboard/projects.$projectId";
import { Route as DashboardUsersIndexRouteImport } from "./routes/_dashboard/users.index";
import { Route as DashboardUsersUserIdRouteImport } from "./routes/_dashboard/users.$userId";
import { Route as DashboardProductsProductIdIndexRouteImport } from "./routes/_dashboard/products.$productId.index";
import { Route as DashboardProductsProductIdEditRouteImport } from "./routes/_dashboard/products.$productId.edit";

const DashboardRoute = DashboardRouteImport.update({
  id: "/_dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const ShopRoute = ShopRouteImport.update({
  id: "/shop",
  path: "/shop",
  getParentRoute: () => rootRouteImport,
} as any);
const SigninRoute = SigninRouteImport.update({
  id: "/signin",
  path: "/signin",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardOperationsRoute = DashboardOperationsRouteImport.update({
  id: "/operations",
  path: "/operations",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardReact19Route = DashboardReact19RouteImport.update({
  id: "/react-19",
  path: "/react-19",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => DashboardRoute,
} as any);
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: "/docs/",
  path: "/docs/",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: "/docs/$slug",
  path: "/docs/$slug",
  getParentRoute: () => rootRouteImport,
} as any);
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: "/landing/",
  path: "/landing/",
  getParentRoute: () => rootRouteImport,
} as any);
const LandingAgencyRoute = LandingAgencyRouteImport.update({
  id: "/landing/agency",
  path: "/landing/agency",
  getParentRoute: () => rootRouteImport,
} as any);
const LandingCourseRoute = LandingCourseRouteImport.update({
  id: "/landing/course",
  path: "/landing/course",
  getParentRoute: () => rootRouteImport,
} as any);
const LandingEventRoute = LandingEventRouteImport.update({
  id: "/landing/event",
  path: "/landing/event",
  getParentRoute: () => rootRouteImport,
} as any);
const LandingProductRoute = LandingProductRouteImport.update({
  id: "/landing/product",
  path: "/landing/product",
  getParentRoute: () => rootRouteImport,
} as any);
const LandingSaasRoute = LandingSaasRouteImport.update({
  id: "/landing/saas",
  path: "/landing/saas",
  getParentRoute: () => rootRouteImport,
} as any);
const LandingStayRoute = LandingStayRouteImport.update({
  id: "/landing/stay",
  path: "/landing/stay",
  getParentRoute: () => rootRouteImport,
} as any);
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ShopRoute,
} as any);
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: "/$productId",
  path: "/$productId",
  getParentRoute: () => ShopRoute,
} as any);
const ShopCartRoute = ShopCartRouteImport.update({
  id: "/cart",
  path: "/cart",
  getParentRoute: () => ShopRoute,
} as any);
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: "/checkout",
  path: "/checkout",
  getParentRoute: () => ShopRoute,
} as any);
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: "/orders/",
  path: "/orders/",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardOrdersOrderIdRoute = DashboardOrdersOrderIdRouteImport.update({
  id: "/orders/$orderId",
  path: "/orders/$orderId",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: "/products/",
  path: "/products/",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardProductsNewRoute = DashboardProductsNewRouteImport.update({
  id: "/products/new",
  path: "/products/new",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: "/projects/",
  path: "/projects/",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: "/projects/$projectId",
    path: "/projects/$projectId",
    getParentRoute: () => DashboardRoute,
  } as any);
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: "/users/",
  path: "/users/",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardUsersUserIdRoute = DashboardUsersUserIdRouteImport.update({
  id: "/users/$userId",
  path: "/users/$userId",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardProductsProductIdIndexRoute =
  DashboardProductsProductIdIndexRouteImport.update({
    id: "/products/$productId/",
    path: "/products/$productId/",
    getParentRoute: () => DashboardRoute,
  } as any);
const DashboardProductsProductIdEditRoute =
  DashboardProductsProductIdEditRouteImport.update({
    id: "/products/$productId/edit",
    path: "/products/$productId/edit",
    getParentRoute: () => DashboardRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof DashboardIndexRoute;
  "/shop": typeof ShopRouteWithChildren;
  "/signin": typeof SigninRoute;
  "/operations": typeof DashboardOperationsRoute;
  "/react-19": typeof DashboardReact19Route;
  "/reports": typeof DashboardReportsRoute;
  "/settings": typeof DashboardSettingsRoute;
  "/docs/$slug": typeof DocsSlugRoute;
  "/landing/agency": typeof LandingAgencyRoute;
  "/landing/course": typeof LandingCourseRoute;
  "/landing/event": typeof LandingEventRoute;
  "/landing/product": typeof LandingProductRoute;
  "/landing/saas": typeof LandingSaasRoute;
  "/landing/stay": typeof LandingStayRoute;
  "/shop/$productId": typeof ShopProductIdRoute;
  "/shop/cart": typeof ShopCartRoute;
  "/shop/checkout": typeof ShopCheckoutRoute;
  "/docs/": typeof DocsIndexRoute;
  "/landing/": typeof LandingIndexRoute;
  "/shop/": typeof ShopIndexRoute;
  "/orders/$orderId": typeof DashboardOrdersOrderIdRoute;
  "/products/new": typeof DashboardProductsNewRoute;
  "/projects/$projectId": typeof DashboardProjectsProjectIdRoute;
  "/users/$userId": typeof DashboardUsersUserIdRoute;
  "/orders/": typeof DashboardOrdersIndexRoute;
  "/products/": typeof DashboardProductsIndexRoute;
  "/projects/": typeof DashboardProjectsIndexRoute;
  "/users/": typeof DashboardUsersIndexRoute;
  "/products/$productId/edit": typeof DashboardProductsProductIdEditRoute;
  "/products/$productId/": typeof DashboardProductsProductIdIndexRoute;
}
export interface FileRoutesByTo {
  "/signin": typeof SigninRoute;
  "/operations": typeof DashboardOperationsRoute;
  "/react-19": typeof DashboardReact19Route;
  "/reports": typeof DashboardReportsRoute;
  "/settings": typeof DashboardSettingsRoute;
  "/docs/$slug": typeof DocsSlugRoute;
  "/landing/agency": typeof LandingAgencyRoute;
  "/landing/course": typeof LandingCourseRoute;
  "/landing/event": typeof LandingEventRoute;
  "/landing/product": typeof LandingProductRoute;
  "/landing/saas": typeof LandingSaasRoute;
  "/landing/stay": typeof LandingStayRoute;
  "/shop/$productId": typeof ShopProductIdRoute;
  "/shop/cart": typeof ShopCartRoute;
  "/shop/checkout": typeof ShopCheckoutRoute;
  "/": typeof DashboardIndexRoute;
  "/docs": typeof DocsIndexRoute;
  "/landing": typeof LandingIndexRoute;
  "/shop": typeof ShopIndexRoute;
  "/orders/$orderId": typeof DashboardOrdersOrderIdRoute;
  "/products/new": typeof DashboardProductsNewRoute;
  "/projects/$projectId": typeof DashboardProjectsProjectIdRoute;
  "/users/$userId": typeof DashboardUsersUserIdRoute;
  "/orders": typeof DashboardOrdersIndexRoute;
  "/products": typeof DashboardProductsIndexRoute;
  "/projects": typeof DashboardProjectsIndexRoute;
  "/users": typeof DashboardUsersIndexRoute;
  "/products/$productId/edit": typeof DashboardProductsProductIdEditRoute;
  "/products/$productId": typeof DashboardProductsProductIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_dashboard": typeof DashboardRouteWithChildren;
  "/shop": typeof ShopRouteWithChildren;
  "/signin": typeof SigninRoute;
  "/_dashboard/operations": typeof DashboardOperationsRoute;
  "/_dashboard/react-19": typeof DashboardReact19Route;
  "/_dashboard/reports": typeof DashboardReportsRoute;
  "/_dashboard/settings": typeof DashboardSettingsRoute;
  "/docs/$slug": typeof DocsSlugRoute;
  "/landing/agency": typeof LandingAgencyRoute;
  "/landing/course": typeof LandingCourseRoute;
  "/landing/event": typeof LandingEventRoute;
  "/landing/product": typeof LandingProductRoute;
  "/landing/saas": typeof LandingSaasRoute;
  "/landing/stay": typeof LandingStayRoute;
  "/shop/$productId": typeof ShopProductIdRoute;
  "/shop/cart": typeof ShopCartRoute;
  "/shop/checkout": typeof ShopCheckoutRoute;
  "/_dashboard/": typeof DashboardIndexRoute;
  "/docs/": typeof DocsIndexRoute;
  "/landing/": typeof LandingIndexRoute;
  "/shop/": typeof ShopIndexRoute;
  "/_dashboard/orders/$orderId": typeof DashboardOrdersOrderIdRoute;
  "/_dashboard/products/new": typeof DashboardProductsNewRoute;
  "/_dashboard/projects/$projectId": typeof DashboardProjectsProjectIdRoute;
  "/_dashboard/users/$userId": typeof DashboardUsersUserIdRoute;
  "/_dashboard/orders/": typeof DashboardOrdersIndexRoute;
  "/_dashboard/products/": typeof DashboardProductsIndexRoute;
  "/_dashboard/projects/": typeof DashboardProjectsIndexRoute;
  "/_dashboard/users/": typeof DashboardUsersIndexRoute;
  "/_dashboard/products/$productId/edit": typeof DashboardProductsProductIdEditRoute;
  "/_dashboard/products/$productId/": typeof DashboardProductsProductIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/shop"
    | "/signin"
    | "/operations"
    | "/react-19"
    | "/reports"
    | "/settings"
    | "/docs/$slug"
    | "/landing/agency"
    | "/landing/course"
    | "/landing/event"
    | "/landing/product"
    | "/landing/saas"
    | "/landing/stay"
    | "/shop/$productId"
    | "/shop/cart"
    | "/shop/checkout"
    | "/docs/"
    | "/landing/"
    | "/shop/"
    | "/orders/$orderId"
    | "/products/new"
    | "/projects/$projectId"
    | "/users/$userId"
    | "/orders/"
    | "/products/"
    | "/projects/"
    | "/users/"
    | "/products/$productId/edit"
    | "/products/$productId/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/signin"
    | "/operations"
    | "/react-19"
    | "/reports"
    | "/settings"
    | "/docs/$slug"
    | "/landing/agency"
    | "/landing/course"
    | "/landing/event"
    | "/landing/product"
    | "/landing/saas"
    | "/landing/stay"
    | "/shop/$productId"
    | "/shop/cart"
    | "/shop/checkout"
    | "/"
    | "/docs"
    | "/landing"
    | "/shop"
    | "/orders/$orderId"
    | "/products/new"
    | "/projects/$projectId"
    | "/users/$userId"
    | "/orders"
    | "/products"
    | "/projects"
    | "/users"
    | "/products/$productId/edit"
    | "/products/$productId";
  id:
    | "__root__"
    | "/_dashboard"
    | "/shop"
    | "/signin"
    | "/_dashboard/operations"
    | "/_dashboard/react-19"
    | "/_dashboard/reports"
    | "/_dashboard/settings"
    | "/docs/$slug"
    | "/landing/agency"
    | "/landing/course"
    | "/landing/event"
    | "/landing/product"
    | "/landing/saas"
    | "/landing/stay"
    | "/shop/$productId"
    | "/shop/cart"
    | "/shop/checkout"
    | "/_dashboard/"
    | "/docs/"
    | "/landing/"
    | "/shop/"
    | "/_dashboard/orders/$orderId"
    | "/_dashboard/products/new"
    | "/_dashboard/projects/$projectId"
    | "/_dashboard/users/$userId"
    | "/_dashboard/orders/"
    | "/_dashboard/products/"
    | "/_dashboard/projects/"
    | "/_dashboard/users/"
    | "/_dashboard/products/$productId/edit"
    | "/_dashboard/products/$productId/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren;
  ShopRoute: typeof ShopRouteWithChildren;
  SigninRoute: typeof SigninRoute;
  DocsSlugRoute: typeof DocsSlugRoute;
  LandingAgencyRoute: typeof LandingAgencyRoute;
  LandingCourseRoute: typeof LandingCourseRoute;
  LandingEventRoute: typeof LandingEventRoute;
  LandingProductRoute: typeof LandingProductRoute;
  LandingSaasRoute: typeof LandingSaasRoute;
  LandingStayRoute: typeof LandingStayRoute;
  DocsIndexRoute: typeof DocsIndexRoute;
  LandingIndexRoute: typeof LandingIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_dashboard": {
      id: "/_dashboard";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/shop": {
      id: "/shop";
      path: "/shop";
      fullPath: "/shop";
      preLoaderRoute: typeof ShopRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/signin": {
      id: "/signin";
      path: "/signin";
      fullPath: "/signin";
      preLoaderRoute: typeof SigninRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_dashboard/": {
      id: "/_dashboard/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/operations": {
      id: "/_dashboard/operations";
      path: "/operations";
      fullPath: "/operations";
      preLoaderRoute: typeof DashboardOperationsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/react-19": {
      id: "/_dashboard/react-19";
      path: "/react-19";
      fullPath: "/react-19";
      preLoaderRoute: typeof DashboardReact19RouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/reports": {
      id: "/_dashboard/reports";
      path: "/reports";
      fullPath: "/reports";
      preLoaderRoute: typeof DashboardReportsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/settings": {
      id: "/_dashboard/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof DashboardSettingsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/docs/": {
      id: "/docs/";
      path: "/docs";
      fullPath: "/docs/";
      preLoaderRoute: typeof DocsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/$slug": {
      id: "/docs/$slug";
      path: "/docs/$slug";
      fullPath: "/docs/$slug";
      preLoaderRoute: typeof DocsSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/landing/": {
      id: "/landing/";
      path: "/landing";
      fullPath: "/landing/";
      preLoaderRoute: typeof LandingIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/landing/agency": {
      id: "/landing/agency";
      path: "/landing/agency";
      fullPath: "/landing/agency";
      preLoaderRoute: typeof LandingAgencyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/landing/course": {
      id: "/landing/course";
      path: "/landing/course";
      fullPath: "/landing/course";
      preLoaderRoute: typeof LandingCourseRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/landing/event": {
      id: "/landing/event";
      path: "/landing/event";
      fullPath: "/landing/event";
      preLoaderRoute: typeof LandingEventRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/landing/product": {
      id: "/landing/product";
      path: "/landing/product";
      fullPath: "/landing/product";
      preLoaderRoute: typeof LandingProductRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/landing/saas": {
      id: "/landing/saas";
      path: "/landing/saas";
      fullPath: "/landing/saas";
      preLoaderRoute: typeof LandingSaasRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/landing/stay": {
      id: "/landing/stay";
      path: "/landing/stay";
      fullPath: "/landing/stay";
      preLoaderRoute: typeof LandingStayRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/shop/": {
      id: "/shop/";
      path: "/";
      fullPath: "/shop/";
      preLoaderRoute: typeof ShopIndexRouteImport;
      parentRoute: typeof ShopRoute;
    };
    "/shop/$productId": {
      id: "/shop/$productId";
      path: "/$productId";
      fullPath: "/shop/$productId";
      preLoaderRoute: typeof ShopProductIdRouteImport;
      parentRoute: typeof ShopRoute;
    };
    "/shop/cart": {
      id: "/shop/cart";
      path: "/cart";
      fullPath: "/shop/cart";
      preLoaderRoute: typeof ShopCartRouteImport;
      parentRoute: typeof ShopRoute;
    };
    "/shop/checkout": {
      id: "/shop/checkout";
      path: "/checkout";
      fullPath: "/shop/checkout";
      preLoaderRoute: typeof ShopCheckoutRouteImport;
      parentRoute: typeof ShopRoute;
    };
    "/_dashboard/orders/": {
      id: "/_dashboard/orders/";
      path: "/orders";
      fullPath: "/orders/";
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/orders/$orderId": {
      id: "/_dashboard/orders/$orderId";
      path: "/orders/$orderId";
      fullPath: "/orders/$orderId";
      preLoaderRoute: typeof DashboardOrdersOrderIdRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/products/": {
      id: "/_dashboard/products/";
      path: "/products";
      fullPath: "/products/";
      preLoaderRoute: typeof DashboardProductsIndexRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/products/new": {
      id: "/_dashboard/products/new";
      path: "/products/new";
      fullPath: "/products/new";
      preLoaderRoute: typeof DashboardProductsNewRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/projects/": {
      id: "/_dashboard/projects/";
      path: "/projects";
      fullPath: "/projects/";
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/projects/$projectId": {
      id: "/_dashboard/projects/$projectId";
      path: "/projects/$projectId";
      fullPath: "/projects/$projectId";
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/users/": {
      id: "/_dashboard/users/";
      path: "/users";
      fullPath: "/users/";
      preLoaderRoute: typeof DashboardUsersIndexRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/users/$userId": {
      id: "/_dashboard/users/$userId";
      path: "/users/$userId";
      fullPath: "/users/$userId";
      preLoaderRoute: typeof DashboardUsersUserIdRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/products/$productId/": {
      id: "/_dashboard/products/$productId/";
      path: "/products/$productId";
      fullPath: "/products/$productId/";
      preLoaderRoute: typeof DashboardProductsProductIdIndexRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/products/$productId/edit": {
      id: "/_dashboard/products/$productId/edit";
      path: "/products/$productId/edit";
      fullPath: "/products/$productId/edit";
      preLoaderRoute: typeof DashboardProductsProductIdEditRouteImport;
      parentRoute: typeof DashboardRoute;
    };
  }
}

interface DashboardRouteChildren {
  DashboardOperationsRoute: typeof DashboardOperationsRoute;
  DashboardReact19Route: typeof DashboardReact19Route;
  DashboardReportsRoute: typeof DashboardReportsRoute;
  DashboardSettingsRoute: typeof DashboardSettingsRoute;
  DashboardIndexRoute: typeof DashboardIndexRoute;
  DashboardOrdersOrderIdRoute: typeof DashboardOrdersOrderIdRoute;
  DashboardProductsNewRoute: typeof DashboardProductsNewRoute;
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRoute;
  DashboardUsersUserIdRoute: typeof DashboardUsersUserIdRoute;
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute;
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute;
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute;
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute;
  DashboardProductsProductIdEditRoute: typeof DashboardProductsProductIdEditRoute;
  DashboardProductsProductIdIndexRoute: typeof DashboardProductsProductIdIndexRoute;
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardOperationsRoute: DashboardOperationsRoute,
  DashboardReact19Route: DashboardReact19Route,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardOrdersOrderIdRoute: DashboardOrdersOrderIdRoute,
  DashboardProductsNewRoute: DashboardProductsNewRoute,
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRoute,
  DashboardUsersUserIdRoute: DashboardUsersUserIdRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardProductsProductIdEditRoute: DashboardProductsProductIdEditRoute,
  DashboardProductsProductIdIndexRoute: DashboardProductsProductIdIndexRoute,
};

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
);

interface ShopRouteChildren {
  ShopProductIdRoute: typeof ShopProductIdRoute;
  ShopCartRoute: typeof ShopCartRoute;
  ShopCheckoutRoute: typeof ShopCheckoutRoute;
  ShopIndexRoute: typeof ShopIndexRoute;
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopProductIdRoute: ShopProductIdRoute,
  ShopCartRoute: ShopCartRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopIndexRoute: ShopIndexRoute,
};

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
  SigninRoute: SigninRoute,
  DocsSlugRoute: DocsSlugRoute,
  LandingAgencyRoute: LandingAgencyRoute,
  LandingCourseRoute: LandingCourseRoute,
  LandingEventRoute: LandingEventRoute,
  LandingProductRoute: LandingProductRoute,
  LandingSaasRoute: LandingSaasRoute,
  LandingStayRoute: LandingStayRoute,
  DocsIndexRoute: DocsIndexRoute,
  LandingIndexRoute: LandingIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
