/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SigninRouteImport } from "./routes/signin";
import { Route as DashboardRouteImport } from "./routes/_dashboard";
import { Route as DashboardIndexRouteImport } from "./routes/_dashboard/index";
import { Route as DashboardSettingsRouteImport } from "./routes/_dashboard/settings";
import { Route as DashboardProjectsIndexRouteImport } from "./routes/_dashboard/projects.index";
import { Route as DashboardProjectsProjectIdRouteImport } from "./routes/_dashboard/projects.$projectId";

const SigninRoute = SigninRouteImport.update({
  id: "/signin",
  path: "/signin",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/_dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: "/projects/",
  path: "/projects/",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: "/projects/$projectId",
    path: "/projects/$projectId",
    getParentRoute: () => DashboardRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof DashboardIndexRoute;
  "/signin": typeof SigninRoute;
  "/settings": typeof DashboardSettingsRoute;
  "/projects/$projectId": typeof DashboardProjectsProjectIdRoute;
  "/projects/": typeof DashboardProjectsIndexRoute;
}
export interface FileRoutesByTo {
  "/signin": typeof SigninRoute;
  "/settings": typeof DashboardSettingsRoute;
  "/": typeof DashboardIndexRoute;
  "/projects/$projectId": typeof DashboardProjectsProjectIdRoute;
  "/projects": typeof DashboardProjectsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_dashboard": typeof DashboardRouteWithChildren;
  "/signin": typeof SigninRoute;
  "/_dashboard/settings": typeof DashboardSettingsRoute;
  "/_dashboard/": typeof DashboardIndexRoute;
  "/_dashboard/projects/$projectId": typeof DashboardProjectsProjectIdRoute;
  "/_dashboard/projects/": typeof DashboardProjectsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    "/" | "/signin" | "/settings" | "/projects/$projectId" | "/projects/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/signin" | "/settings" | "/" | "/projects/$projectId" | "/projects";
  id:
    | "__root__"
    | "/_dashboard"
    | "/signin"
    | "/_dashboard/settings"
    | "/_dashboard/"
    | "/_dashboard/projects/$projectId"
    | "/_dashboard/projects/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren;
  SigninRoute: typeof SigninRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/signin": {
      id: "/signin";
      path: "/signin";
      fullPath: "/signin";
      preLoaderRoute: typeof SigninRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_dashboard": {
      id: "/_dashboard";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_dashboard/": {
      id: "/_dashboard/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/settings": {
      id: "/_dashboard/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof DashboardSettingsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/projects/": {
      id: "/_dashboard/projects/";
      path: "/projects";
      fullPath: "/projects/";
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/projects/$projectId": {
      id: "/_dashboard/projects/$projectId";
      path: "/projects/$projectId";
      fullPath: "/projects/$projectId";
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport;
      parentRoute: typeof DashboardRoute;
    };
  }
}

interface DashboardRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRoute;
  DashboardIndexRoute: typeof DashboardIndexRoute;
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRoute;
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute;
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
};

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  SigninRoute: SigninRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
